#################
# Configuration #
#################
exclude: []
future: false
plugins:
  - jekyll-seo-tag
sass:
  load_paths:
    - assets/stylesheets
    - node_modules

title: "Kayla Glick | Web Developer"

skills:
  agile:
    text: "Agile / Scrum"
    proficiency: 5
  bootstrap:
    text: "Bootstrap (3 & 4)"
    proficiency: 5
  html:
    text: "HTML(5)"
    proficiency: 5
  json:
    text: "JSON"
    proficiency: 5
  rails:
    text: "(Ruby) on Rails"
    proficiency: 5
  scss:
    text: "(S)CSS"
    proficiency: 5
  coffeescript:
    text: "Coffeescript (1 & 2)"
    proficiency: 4
  git:
    text: "Git(Hub)"
    proficiency: 4
  javascript:
    text: "JavaScript (ES6+)"
    proficiency: 4
  jQuery:
    text: "jQuery"
    proficiency: 4
  mysql:
    text: "MySQL"
    proficiency: 4
  rest:
    text: "REST"
    proficiency: 4
  uml:
    text: "UML"
    proficiency: 4
  java:
    text: "Java"
    proficiency: 3
  nodejs:
    text: "Node.js"
    proficiency: 3
  yarn:
    text: "Yarn"
    proficiency: 3
  bash:
    text: "Bash"
    proficiency: 2
  react:
    text: "React"
    proficiency: 1

employers:
  musc:
    employer: "Medical University of South Carolina"
    employer_short: "MUSC"
    role: "Web Developer"
    dates: "Oct 2018 - Present"
    location: "Remote / Charleston, SC"
    link: "https://sparc.musc.edu/"
    responsibilities:
      - "Full stack development of open-source web applications for medical research at institutions across the U.S."
      - "Collaborate with a diverse team of developers, analysts, and open-source contributors on a daily basis."
      - "Design and coordinate projects to overhaul UX and back-end architecture of existing applications using Ruby on Rails, JavaScript, Bootstrap 4, and Node.js."
      - "Develop extensive unit, integration, and system tests using RSpec and Selenium Webdriver."

  musc_intern:
    employer: "Medical University of South Carolina"
    employer_short: "MUSC (Intern)"
    role: "Intern"
    dates: "Jun 2015 - Sept 2018"
    location: "Charleston, SC"
    link: "https://sparc.musc.edu/"
    responsibilities:
      - "Developed open-source web applications for medical research at institutions across the U.S. using Ruby on Rails and JavaScript."
      - "Interfaced with analysts to devise new functionality and improvements to existing systems."
      - "Led major overhauls of existing interfaces using Bootstrap 3."
      - "Wrote extensive unit, integration, and system tests using RSpec and Selenium Webdriver."

portfolio:
  target_charts:
    name: "Target Charts"
    description: "A web application for tracking and visualizing production targets, developed for my senior capstone project in collaboration with Bosch Charleston. Includes customizable visualization, efficient data entry, and full responsiveness."
    featured: "true"
    tags:
      - Ruby on Rails
      - Bootstrap
      - jQuery
    links:
      github: "https://github.com/Anderson-Lab/capstone-spring-2018-team-4"
      youtube: "https://www.youtube.com/watch?v=ShAVnZbSqfY&feature=youtu.be"
  360snoozin:
    name: "360Snoozin"
    description: "A dual-alarm AM/FM radio clock application developed for my Software Architecture and Design class. Uses multi-threading to accomplish asynchronous timing and radio functionality."
    featured: "true"
    tags:
      - JavaFX
      - Bootstrap
      - jQuery
    links:
      github: "https://github.com/kayla-glick/360Snoozin"
  movedb:
    name: "MovEDB"
    description: "A movie ticketing and theater management web application developed for my Database Concepts class. Open new theaters, choose which movies to show, and allow moviegoers to purchase tickets."
    featured: "true"
    tags:
      - PHP
      - Bootstrap
      - jQuery
    links:
      github: "https://github.com/kayla-glick/csci-332"
