#################
# Configuration #
#################
exclude: []
future: false
plugins:
  - jekyll-seo-tag
sass:
  load_paths:
    - assets/stylesheets
    - node_modules

title: "Kayla Glick | Web Developer"

skills:
  languages:
    ruby:
      text: "Ruby"
      proficiency: 5
    html:
      text: "HTML"
      proficiency: 5
    sass:
      text: "CSS / Sass"
      proficiency: 5
    javascript:
      text: "JavaScript (ES6+)"
      proficiency: 4
      proficiency: 4
    sql:
      text: "SQL"
      proficiency: 4
    bash:
      text: "Bash"
      proficiency: 2
  frameworks:
    rails:
      text: "Ruby on Rails"
      proficiency: 5
    bootstrap:
      text: "Bootstrap"
      proficiency: 5
    jQuery:
      text: "jQuery"
      proficiency: 4
    react:
      text: "React"
      proficiency: 3
    graphql:
      text: "GraphQL"
      proficiency: 3
    nodejs:
      text: "Node.js"
      proficiency: 2
  tools:
    git:
      text: "Git"
      proficiency: 5
    json:
      text: "JSON"
      proficiency: 5
    yaml:
      text: "YAML"
      proficiency: 5
    github:
      text: "GitHub"
      proficiency: 5
    pivotal:
      text: "Storyboards (Pivotal, Jira)"
      proficiency: 4
    mysql:
      text: "MySQL"
      proficiency: 4
  principles:
    agile:
      text: "Agile / Scrum"
      proficiency: 5
    mvc:
      text: "Model-View-Controller"
      proficiency: 5
    rest:
      text: "RESTful Architecture"
      proficiency: 4
    saas:
      text: "Software as a Service"
      proficiency: 4
    tdd:
      text: "Test-Driven-Development"
      proficiency: 4
    ci:
      text: "Continuous Integration"
      proficiency: 4

roles:
  dutchie_soft_eng:
    employer: "Dutchie"
    employer_link: "https://dutchie.com/"
    role: "Senior Software Engineer"
    dates: "Mar 2021 - Present"
    year: "2021"
    location: "Remote"
    responsibilities:
      - "Designing and planning a top-secret payments infrastructure for dutchie's e-commerce platform."
      - "Collaborating with product and design teams to plan new payments workflows."
      - "Creating and managing Jira tickets and sprint planning for my team."
      - "Mentoring other teammates in the dutchie back-end stack."
      - "More details to come!"
  musc_senior_web_dev:
    employer: "MUSC"
    employer_link: "https://web.musc.edu/"
    role: "Senior Web Developer"
    dates: "Jan 2020 - Feb 2021"
    year: "2020"
    location: "Remote / Charleston, SC"
    responsibilities:
      - "Develop and manage open-source Ruby on Rails web applications."
      - "Collaborate with stakeholders to plan new features, sprints and releases."
      - "Manage storyboards, pull requests, and code deployments to meet sprint deadlines."
      - "Design and update interfaces according to UX and accessibility principles."
      - "Refactor back-end architecture to improve performance of applications."
  musc_web_dev:
    employer: "MUSC"
    employer_link: "https://web.musc.edu/"
    role: "Web Developer"
    year: "2018"
    dates: "Oct 2018 - Dec 2019"
    location: "Remote / Charleston, SC"
    responsibilities:
      - "Collaborated with a team of developers, analysts, and contributors to develop the full stack of open-source web applications for MUSC."
      - "Interfaced with analysts to devise new requirements for and make improvements to existing applications."
      - "Led multiple projects to improve front-end interfaces and back-end architectural performance."
      - "Wrote comprehensive automated unit and integration tests."
  musc_intern:
    employer: "MUSC"
    employer_link: "https://web.musc.edu/"
    role: "Web Developer Intern"
    dates: "Jun 2015 - Sept 2018"
    year: "2015"
    location: "Charleston, SC"

portfolio:
  sparcrequest:
    name: "SPARCRequest"
    description: "An open-source web-based research management system developed by my team under the South Carolina Clinical & Translational Research Institute that integrates research and clinical care workflows."
    featured: "true"
    tags:
      - Ruby on Rails
      - Bootstrap 4
      - JavaScript (ES6)
      - jQuery
    links:
      github: "https://github.com/sparc-request/sparc-request"
      external-link-alt: "https://sparc.musc.edu"
  living_biobank:
    name: "Living BioBank"
    description: "An open-source web application developed by myself and a few other collaborators under the Medical University of South Carolina Biomedical Informatics Center for the capture and delivery of de-identified clinical data and phenotyped specimens."
    featured: "true"
    tags:
      - Ruby on Rails
      - Bootstrap 4
      - JavaScript (ES6)
      - jQuery
    links:
      github: "https://github.com/living-biobank/living-biobank"
      external-link-alt: "https://lbb.musc.edu"
  target_charts:
    name: "Target Charts"
    description: "A web application developed and presented for my senior capstone team project in collaboration with Bosch Charleston that integrates data management, tracking, and in-depth and customizable visualization of production target tracking."
    featured: "true"
    tags:
      - Ruby on Rails
      - Bootstrap 4
      - jQuery
    links:
      github: "https://github.com/Anderson-Lab/capstone-spring-2018-team-4"
      youtube: "https://www.youtube.com/watch?v=ShAVnZbSqfY&feature=youtu.be"
  360snoozin:
    name: "360Snoozin"
    description: "A dual-alarm AM/FM radio clock application developed for my Software Architecture and Design class. Uses multi-threading to accomplish asynchronous timing and radio functionality."
    featured: "false"
    tags:
      - JavaFX
      - Bootstrap
      - jQuery
    links:
      github: "https://github.com/kayla-glick/360Snoozin"
  movedb:
    name: "MovEDB"
    description: "A movie ticketing and theater management web application developed for my Database Concepts class. Open new theaters, choose which movies to show, and allow moviegoers to purchase tickets."
    featured: "false"
    tags:
      - PHP
      - SQL
      - Bootstrap
      - jQuery
    links:
      github: "https://github.com/kayla-glick/csci-332"
