#################
# Configuration #
#################
exclude: []
future: false
plugins:
  - jekyll-coffeescript
  - jekyll-seo-tag
sass:
  load_paths:
    - assets/stylesheets
    - node_modules
title: "Kyle Glick | Full-Stack Developer"

skills:
  languages:
    - Ruby
    - JavaScript (ES6)
    - TypeScript
    - HTML5
    - CSS/SASS
    - SQL
  frameworks:
    - Ruby on Rails
    - ReactJS
    - Node.js
    - AJAX
    - jQuery
    - Bootstrap
  utilities:
    - Git (GitHub)
    - Pivotal Tracker
    - Zenhub
    - MySQL
    - Travis CI
    - AWS
  methodologies:
    - Scrum / Agile
    - RESTFul Architecture
    - Test-Driven Development
    - Continuous Integration

experience:
  musc:
    employer: "Medical University of SC"
    website: "https://www.musc.edu"
    role: "Full-Stack Developer"
    dates: "June 2015 - Present"
    location: "Charleston, SC / Remote"
    tasks:
      - "Collaborated with a team of developers and from various institutions to build complex open-source Ruby on Rails web applications used to manage costs and services for clinical research studies."
      - "Interfaced with systems analysts to write and test new functionality and fix bugs in short scrum sprints."
      - "Drafted and built major new modules and lead modernization of existing portions of applications."
  bosch:
    employer: "Bosch"
    website: "https://www.bosch.com/"
    role: "Full-Stack Developer, Scrum Master"
    dates: "Jan - May 2018"
    location: "Charleston, SC"
    tasks:
      - "Collaborated with a small team of CofC students and Bosch employees to design a Ruby on Rails application for managing production targets."
      - "Alternated roles as Scrum Master to plan sprints and manage team progress."

portfolio:
  csci_462:
    name: "Target Charts"
    description: "A business target management and visualization tool built by CofC students in collaboration with Bosch Charleston."
    featured: "true"
    tags:
      - Rails
      - Ruby
      - JavaScript
      - HTML
      - CSS
      - MySQL
    links:
      github: "https://github.com/Anderson-Lab/capstone-spring-2018-team-4"
      youtube: "https://www.youtube.com/watch?v=ShAVnZbSqfY&feature=youtu.be"
  csci_362:
    name: "Testing Canvas"
    description: "An automated test suite built around the Canvas LMS source code for a Software Engineering class."
    featured: "false"
    tags:
      - Ruby
      - Bash
    links:
      github: "https://github.com/kyle-glick/Don-t-Test-Me"
  csci_360:
    name: "360Snoozin"
    description: "A dual-alarm AM/FM radio clock built with JavaFX for a Software Architecture and Design class."
    featured: "true"
    tags:
      - JavaFX
      - Java
      - HTML
      - CSS
    links:
      github: "https://github.com/kyle-glick/360Snoozin"
  csci_332:
    name: "MovEDB"
    description: "A simple movie ticket and theater management website built with PHP for a Database Concepts class."
    featured: "true"
    tags:
      - PHP
      - JavaScript
      - HTML
      - CSS
      - MySQL
    links:
      github: "https://github.com/kyle-glick/csci-332"

blog:
  csci_362_blog:
    name: "Software Engineering Blog"
    description: "A blog for my Software Engineering class at College of Charleston, taught by <a href='http://stono.cs.cofc.edu/~bowring/' target='_blank'>Dr. Jim Bowring</a>, where I discuss various topics related to software engineering through various readings and my textbook, <a href='http://iansommerville.com/software-engineering-book/' target='_blank'><em>Software Engineering 10th Edition</em></a> by Ian Sommerville."
