plugins: [jekyll-paginate, jekyll-paginate-categories]

paginate: 5
paginate_path: "/p/:num/"

paginate_category_basepath: "/projects/:name/"
paginate_category_layout: "category.html"

projects:
  csci_362:
    title: "CSCI 362 Blog"
    description: "A blog for my CSCI 362 - Software Engineering class taught by Dr. Jim Bowring where I discuss ethical issues in Software Engineering and complete various homework from Ian Sommerville's book <em>Software Engineering 10th Edition</em>."
    date: "Fall 2017"
    logo: "/assets/images/csci_362/logo.jpg"
  sparcrequest:
    title: "SPARCRequest"
    description: "A blog dedicated to my work on the SPARCRequest team at the Medical University of South Carolina Biomedical Informatics Center."
    date: "Summer 2015 - Present"
    logo: "/assets/images/sparcrequest/logo.jpg"
