#################
# Configuration #
#################
exclude: []
future: false
plugins:
  - jekyll-coffeescript
  - jekyll-seo-tag
sass:
  load_paths:
    - assets/stylesheets
    - node_modules
title: "Kyle Glick | Full Stack Developer"

per_page: 5

portfolio:
  sparcrequest:
    title: "MUSC Biomedical Informatics Center - Student Intern"
    description: "I worked as an intern at the Biomedical Informatics Center at the Medical University of South Carolina to maintain and develop for the SPARCRequest team, consisting of several applications dedicated to research management built with Ruby on Rails."
    date: "Summer 2015 - Present"
    logo: "/assets/images/sparcrequest/bmic_logo.png"
  csci_360:
    title: "CSCI 360 Software Architecture and Design - Alarm Clock"
    description: "I worked with two other students to build a Dual-Alarm AM/FM Clock Radio application using JavaFX. We also drafted a report detailing the various steps of the design process."
    date: "Spring 2017"
    logo: "/assets/images/csci_360/logo.png"
