#################
# Configuration #
#################
exclude: []
future: false
plugins:
  - jekyll-seo-tag
sass:
  load_paths:
    - assets/stylesheets
    - node_modules

title: "Kayla Glick | Web Developer"

skills:
  agile:
    text: "Agile / Scrum"
    proficiency: 5
  bootstrap:
    text: "Bootstrap (3 & 4)"
    proficiency: 5
  html:
    text: "HTML(5)"
    proficiency: 5
  json:
    text: "JSON"
    proficiency: 5
  rails:
    text: "(Ruby) on Rails"
    proficiency: 5
  scss:
    text: "(S)CSS"
    proficiency: 5
  coffeescript:
    text: "Coffeescript (1 & 2)"
    proficiency: 4
  git:
    text: "Git(Hub)"
    proficiency: 4
  javascript:
    text: "JavaScript (ES6+)"
    proficiency: 4
  jQuery:
    text: "jQuery"
    proficiency: 4
  mysql:
    text: "MySQL"
    proficiency: 4
  rest:
    text: "REST"
    proficiency: 4
  uml:
    text: "UML"
    proficiency: 4
  java:
    text: "Java"
    proficiency: 3
  nodejs:
    text: "Node.js"
    proficiency: 3
  yarn:
    text: "Yarn"
    proficiency: 3
  bash:
    text: "Bash"
    proficiency: 2
  react:
    text: "React"
    proficiency: 1


employers:
  musc:
    employer: "Medical University of South Carolina"
    employer_short: "MUSC"
    role: "Web Developer"
    dates: "Oct 2018 - Present"
    location: "Remote / Charleston, SC"
    link: "https://sparc.musc.edu/"
    responsibilities:
      - "Full stack development of open-source web applications for medical research at institutions across the U.S."
      - "Collaborate with a diverse team of developers, analysts, and open-source contributors on a daily basis."
      - "Design and coordinate projects to overhaul UX and back-end architecture of existing applications using Ruby on Rails, JavaScript, Bootstrap 4, and Node.js."
      - "Develop extensive unit, integration, and system tests using RSpec and Selenium Webdriver."

  musc_intern:
    employer: "Medical University of South Carolina"
    employer_short: "MUSC (Intern)"
    role: "Intern"
    dates: "Jun 2015 - Sept 2018"
    location: "Charleston, SC"
    link: "https://sparc.musc.edu/"
    responsibilities:
      - "Developed open-source web applications for medical research at institutions across the U.S. using Ruby on Rails and JavaScript."
      - "Interfaced with analysts to devise new functionality and improvements to existing systems."
      - "Led major overhauls of existing interfaces using Bootstrap 3."
      - "Wrote extensive unit, integration, and system tests using RSpec and Selenium Webdriver."
portfolio:
  csci_462:
    name: "Target Charts"
    description: "A business target management and visualization tool built by CofC students in collaboration with Bosch Charleston."
    featured: "true"
    tags:
      - Rails
      - Ruby
      - JavaScript
      - HTML
      - CSS
      - MySQL
    links:
      github: "https://github.com/Anderson-Lab/capstone-spring-2018-team-4"
      youtube: "https://www.youtube.com/watch?v=ShAVnZbSqfY&feature=youtu.be"
  csci_362:
    name: "Testing Canvas"
    description: "An automated test suite built around the Canvas LMS source code for a Software Engineering class."
    featured: "false"
    tags:
      - Ruby
      - Bash
    links:
      github: "https://github.com/kyle-glick/Don-t-Test-Me"
  csci_360:
    name: "360Snoozin"
    description: "A dual-alarm AM/FM radio clock built with JavaFX for a Software Architecture and Design class."
    featured: "true"
    tags:
      - JavaFX
      - Java
      - HTML
      - CSS
    links:
      github: "https://github.com/kyle-glick/360Snoozin"
  csci_332:
    name: "MovEDB"
    description: "A simple movie ticket and theater management website built with PHP for a Database Concepts class."
    featured: "true"
    tags:
      - PHP
      - JavaScript
      - HTML
      - CSS
      - MySQL
    links:
      github: "https://github.com/kyle-glick/csci-332"
