#################
# Configuration #
#################
exclude: []
future: false
plugins:
  - jekyll-coffeescript
  - jekyll-seo-tag
sass:
  load_paths:
    - assets/stylesheets
    - node_modules
title: "Kyle Glick | Full-Stack Developer"

experience:
  musc:
    employer: "Medical University of South Carolina"
    website: "https://www.musc.edu"
    role: "Full-Stack Developer"
    dates: "June 2015 - Aug 2018"
  bosch:
    employer: "Bosch"
    website: "https://www.bosch.com/"
    role: "Full-Stack Developer, Scrum Master"
    dates: "Jan - May 2018"

portfolio:
  csci_462:
    name: "Target Charts"
    description: "Production target management and visualization website for Bosch designed by a team of College of Charleston students and built with Ruby on Rails."
    featured: "true"
    tags:
      - Rails
      - Ruby
      - JavaScript
      - HTML
      - CSS
      - MySQL
    links:
      github: "https://github.com/kyle-glick/capstone-spring-2018-team-4"
      youtube: "https://www.youtube.com/watch?v=ShAVnZbSqfY&feature=youtu.be"
  csci_362:
    name: "Canvas Test Framework"
    description: ""
    featured: "false"
    tags:
      - Ruby
      - Bash
    links:
      github: "https://github.com/kyle-glick/Don-t-Test-Me"
  csci_360:
    name: "360Snoozin Clock"
    description: "Dual-Alarm AM/FM Radio Clock built with JavaFX for a Software Architecture and Design class."
    featured: "true"
    tags:
      - JavaFX
      - Java
      - HTML
      - CSS
    links:
      github: "https://github.com/kyle-glick/360Snoozin"
  csci_332:
    name: "MovEDB"
    description: "Simple movie ticket and theater management website built with PHP for a Database Concepts class."
    featured: "true"
    tags:
      - PHP
      - JavaScript
      - HTML
      - CSS
      - MySQL
    links:
      github: "https://github.com/kyle-glick/csci-332"

blog:
  csci_362_blog:
    name: "Software Engineering Blog"
    description: "A blog for my Software Engineering class at College of Charleston, taught by <a href='http://stono.cs.cofc.edu/~bowring/' target='_blank' class='underline-link'>Dr. Jim Bowring</a>, where I discuss various topics related to software engineering through various readings and my textbook, <a href='http://iansommerville.com/software-engineering-book/' target='_blank' class='underline-link'><em>Software Engineering 10th Edition</em></a> by Ian Sommerville."
