#################
# Configuration #
#################
exclude: []
future: false
plugins:
  - jekyll-seo-tag
sass:
  load_paths:
    - assets/stylesheets
    - node_modules

title: "Kayla Glick | Senior Software Engineer"

skills:
  languages_frameworks:
    rails:
      text: "Ruby on Rails"
      proficiency: 5
    javascript:
      text: "JavaScript (ES6+)"
      proficiency: 5
    html:
      text: "HTML5"
      proficiency: 5
    json:
      text: "JSON"
      proficiency: 5
    bootstrap:
      text: "Bootstrap"
      proficiency: 4
    sass:
      text: "CSS & Sass"
      proficiency: 4
    sql:
      text: "SQL"
      proficiency: 4
    grpc:
      text: "gRPC"
      proficiency: 4
    graphql:
      text: "GraphQL"
      proficiency: 3
    react:
      text: "React"
      proficiency: 3
  tools_principles:
    apis:
      text: "REST & RPC APIs"
      proficiency: 5
    agile:
      text: "Agile Development"
      proficiency: 5
    datamodels:
      text: "Data Modeling"
      proficiency: 5
    flowchart:
      text: "Flowchart Design"
      proficiency: 5
    projman:
      text: "Project Management"
      proficiency: 4
    ux:
      text: "UX Design Principles"
      proficiency: 4
    git:
      text: "Git Version Control"
      proficiency: 4
    storyboards:
      text: "Storyboards"
      proficiency: 4
    automation:
      text: "Test Automation"
      proficiency: 4

roles:
  github_senior:
    employer: "GitHub"
    employer_link: "https://github.com"
    role: "Senior Software Engineer"
    dates: "Aug 2022 - Present"
    year: "Present"
    location: "Remote"
    responsibilities:
      - "Building software for GitHub's #gitcoin billing team."

  dutchie_senior_2:
    employer: "Dutchie"
    employer_link: "https://dutchie.com/"
    role: "Tech Lead, Senior Software Engineer II"
    dates: "Nov 2021 - June 2022"
    year: "2022"
    location: "Remote"
    responsibilities:
      - "Tech lead and consulting engineer for Dutchie’s online payments team."
      - "Architect for the workflows, services, and underlying data models supporting Dutchie’s in-house payments service, Dutchie Pay."
      - "Drafted engineering project blueprints from product specifications and design mock-ups, and consult on blueprints from other teams."
      - "Developed high-level estimates to help determine project timelines and resource estimation."
      - "Created and manage Jira tickets and sprint storyboards for the online payments team."
      - "Managed releases and deployments using Git & Heroku Enterprise."
      - "Drove incident investigation and response using Datadog, Rollbar, and the Heroku console."
      - "Mentored and provided guidance to other members of the team."

  dutchie_senior:
    employer: "Dutchie"
    employer_link: "https://dutchie.com/"
    role: "Senior Software Engineer"
    dates: "Mar 2021 - Nov 2021"
    year: "2021"
    location: "Remote"
    responsibilities:
      - "Developed a new full-stack platform for accepting online credit card payments with Rails, GraphQL, and React."
      - "Began investigation and initial planning for Dutchie’s in-house payments platform."
      - "Devised new patterns to consolidate Dutchie’s back-end service objects."
      - "Proposed improvements to Dutchie’s back-end testing practices."

  musc_senior_web_dev:
    employer: "Medical University of SC"
    employer_link: "https://web.musc.edu/"
    role: "Senior Web Developer"
    dates: "Jan 2020 - Feb 2021"
    year: "2020"
    location: "Remote"
    responsibilities:
      - "Collaborate with stakeholders to plan new features, sprints and releases."
      - "Managed storyboards, pull requests, and code deployments to meet sprint deadlines."
      - "Refactored multiple back-end components to improve application performance"
      - "Trained new developers and provided advice, support, and guidance as needed."
      - "Performed thorough review and provided feedback on all code contributions."

  musc_web_dev:
    employer: "Medical University of SC"
    employer_link: "https://web.musc.edu/"
    role: "Web Developer"
    year: "2018"
    dates: "Oct 2018 - Dec 2019"
    location: "Remote"
    responsibilities:
      - "Joined the same team I had interned for after graduation, performing many of the same roles as I had previously."
      - "Led multiple projects to improve front-end UX, including implementing Bootstrap and re-designing multiple sections of our applications."
      - "Interfaced with analysts to devise new requirements for and make improvements to existing applications."

  musc_intern:
    employer: "Medical University of SC"
    employer_link: "https://web.musc.edu/"
    role: "Intern Web Developer"
    dates: "Jun 2015 - Sept 2018"
    year: "2015"
    location: "Charleston, SC"
    responsibilities:
      - "Learned Ruby on Rails, HTML, JavaScript and web development concepts from scratch while attending school."
      - "Collaborated with other interns and full-time developers to build and maintain full-stack Ruby on Rails web applications."
      - "Improved upon existing RSpec and Capybara tests to provide more-comprehensive test coverage."

recipes:
  onigirazu:
    name: "Japanese Onigirazu"
    labels:
  black_bean_burgers:
    name: "Black Bean Burgers"
    labels:
      - (V)
  spaghetti:
    name: "Spaghetti"
    labels:
      - (VE)
  cajun_pasta:
    name: "Creamy Cajun Chicken Pasta"
    labels:
  brownies:
    name: "Gooey Dark Chocolate Brownies"
    labels:
      - (V)

portfolio:
  dutchiepay:
    name: "Dutchie Pay"
    description: "Dutchie Pay is Dutchie's premiere in-house ACH payments platform. I designed a significant portion of the underlying workflow, consumer-facing APIs, and supporting data models, as well as lead the team's development from concept to reality."
    featured: "true"
    tags:
      - Ruby on Rails
      - gRPC
      - Software Architecture
      - Data Modeling
    links:
      external-link-alt: "https://business.dutchie.com/payments"
  sparcrequest:
    name: "SPARCRequest"
    description: "An open-source web-based research management system developed by my team under the South Carolina Clinical & Translational Research Institute that integrates research and clinical care workflows."
    featured: "true"
    tags:
      - Ruby on Rails
      - Bootstrap 4
      - JavaScript (ES6)
      - jQuery
    links:
      github: "https://github.com/sparc-request/sparc-request"
      external-link-alt: "https://sparc.musc.edu"
  living_biobank:
    name: "Living BioBank"
    description: "An open-source web application developed by myself and a few other collaborators under the Medical University of South Carolina Biomedical Informatics Center for the capture and delivery of de-identified clinical data and phenotyped specimens."
    featured: "true"
    tags:
      - Ruby on Rails
      - Bootstrap 4
      - JavaScript (ES6)
      - jQuery
    links:
      github: "https://github.com/living-biobank/living-biobank"
      external-link-alt: "https://lbb.musc.edu"
  target_charts:
    name: "Target Charts"
    description: "A web application developed and presented for my senior capstone team project in collaboration with Bosch Charleston that integrates data management, tracking, and in-depth and customizable visualization of production target tracking."
    featured: "true"
    tags:
      - Ruby on Rails
      - Bootstrap 4
      - jQuery
    links:
      github: "https://github.com/Anderson-Lab/capstone-spring-2018-team-4"
      youtube: "https://www.youtube.com/watch?v=ShAVnZbSqfY&feature=youtu.be"
  360snoozin:
    name: "360Snoozin"
    description: "A dual-alarm AM/FM radio clock application developed for my Software Architecture and Design class. Uses multi-threading to accomplish asynchronous timing and radio functionality."
    featured: "false"
    tags:
      - JavaFX
      - Bootstrap
      - jQuery
    links:
      github: "https://github.com/kayla-glick/360Snoozin"
  movedb:
    name: "MovEDB"
    description: "A movie ticketing and theater management web application developed for my Database Concepts class. Open new theaters, choose which movies to show, and allow moviegoers to purchase tickets."
    featured: "false"
    tags:
      - PHP
      - SQL
      - Bootstrap
      - jQuery
    links:
      github: "https://github.com/kayla-glick/csci-332"
